### ISSUE TITLE
OSX 10.11 "El Capitan" make fails

### ISSUE THREAD

**Issue by josecanciani** [alperakcan/fuse-ext2#10] opened 2015-07-20 23:10 UTC
Hello. I've installed El Capitan and I'm trying to build ext2fuse.

I've installed OSXFUSE 2.8 (which should work with El Capitan). I also have Xcode 7 beta and it's Command Line tools (I had to run xcode-select --switch pointing to the Xcode beta path).

Then I've installed e2fsprogs with homebrew and I was able to run the configure script of ext2fuse with this environment:

``` bash
$ CFLAGS="-idirafter/usr/local/Cellar/e2fsprogs/1.42.12/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L/usr/local/Cellar/e2fsprogs/1.42.12/lib" ./configure
```

But when I try "make" it seems everything goes as planned until it reaches this error:

``` bash
$ make
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make  all-recursive
Making all in fuse-ext2
make[2]: Nothing to be done for 'all'.
Making all in tools
Making all in macosx
( cd ../../tools/macosx/prefpane; \
      xcodebuild; \
    )
=== BUILD TARGET fuse-ext2 OF PROJECT fuse-ext2 WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
error: There is no SDK with the name or path '/Users/joe/Sites/fuse-ext2/tools/macosx/prefpane/macosx10.9'

** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
make[3]: *** [prefpane] Error 65
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Any ideas?

Thanks,
Jose

**Comment by colindean** [comment] 2015-07-22 00:57
This configure line worked better for me. It doesn't hardcode package versions. I'm on Mavericks.

```
CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure
```

**Comment by josecanciani** [comment] 2015-07-22 04:22
Yeah, it's cleaner, but it doesn't fix the original problem :(

**Comment by alperakcan** [comment] 2015-08-07 23:00
can you please try again with commit 6fa1c01f133581f027b8dcda0e890bcbb8053b26

**Comment by josecanciani** [comment] 2015-08-08 14:41
Yes, make ended without errors! But the sudo make install is getting this:

$ sudo make install
Making install in fuse-ext2
 .././install-sh -c -d '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c fuse-ext2 fuse-ext2.probe fuse-ext2.wait fuse-ext2.install fuse-ext2.uninstall '/usr/local/bin'
libtool: install: /usr/bin/install -c fuse-ext2 /usr/local/bin/fuse-ext2
libtool: install: /usr/bin/install -c fuse-ext2.probe /usr/local/bin/fuse-ext2.probe
libtool: install: /usr/bin/install -c fuse-ext2.wait /usr/local/bin/fuse-ext2.wait
libtool: install: /usr/bin/install -c fuse-ext2.install /usr/local/bin/fuse-ext2.install
libtool: install: /usr/bin/install -c fuse-ext2.uninstall /usr/local/bin/fuse-ext2.uninstall
/usr/bin/install -c -d "/sbin"
install: chmod 755 /sbin: Operation not permitted
ln -s -f "../System/Library/Filesystems/fuse-ext2.fs/mount_fuse-ext2" "/sbin/mount_fuse-ext2"
ln: /sbin/mount_fuse-ext2: Operation not permitted
make[2]: *** [install-exec-local] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

**Comment by josecanciani** [comment] 2015-08-08 14:46
I'll update Xcode from beta 3 to current beta 5 and I'll let you know.

**Comment by josecanciani** [comment] 2015-08-08 14:57
It seems that won't work, it has to do with the new rootless feature, no-one can touch the /sbin folder:
http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html

Can we change the install script to install elsewhere? Will it automatically mount if we do?

**Comment by jgclark** [comment] 2015-08-13 17:44
Same issue as @josecanciani: the make install fails because of /sbin mentions. I tried changing the Makefile accordingly, but am too rusty on how these things work.

**Comment by josecanciani** [comment] 2015-08-13 23:23
I tried creating /usr/loca/sbin and then running both with:
   ./configure --sbindir=/usr/local/sbin
   sudo make install exec_prefix=/usr/local
and it gave the same error:
  /usr/bin/install -c -d "/sbin"
  install: chmod 755 /sbin: Operation not permitted

The /sbin dir must be hardcoded somewhere. But again I don't know if fuse-ext2 can work from another directory.

Any ideas?

Jose

**Comment by jgclark** [comment] 2015-08-19 23:10
I tried the first of your commands, @josecanciani but this is the different error I got:

```
...
checking for lseek64... no
checking for library containing sem_post... none required
checking for library containing fuse_main... no
configure: error: Can't find libfuse, please install it
```

**Comment by muammar** [comment] 2015-09-30 23:10
I also tried to configure to build from source but I get:

```
checking for uname... yes
checking for utime... yes
checking for llseek... no
checking for lseek64... no
checking for library containing sem_post... none required
checking for library containing fuse_main... no
configure: error: Can't find libfuse, please install it
```

FUSE for OS X seems to be correctly installed.

**Comment by muammar** [comment] 2015-10-01 08:51
I "solved" this partially by installing the fuse-ext2 binary after disabling rootless as shown in here:

http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html

**Comment by jgclark** [comment] 2015-10-03 20:13
Like @muammar I disabled SIP and then it seemed to build and install OK. But it failed on the tests shown in the README, not finding the files listed.

I plugged in a very old external disk with what I think are ext2 partitions, and diskutil reports that it's mounted them as ext2, without me doing anything. Should this be the behaviour? I was still expecting to have to mount manually. The 2 mounted ext2 partitions are completely empty, which is suspicious.

**Comment by muammar** [comment] 2015-10-04 08:59
@jgclark I didn't do the tests in README, but so far I can access my ext4 partition with writing support as usual. 

Normally, the partitions are mounted automatically. In my case, I can access all content in the partitions.

**Comment by jgclark** [comment] 2015-10-04 12:14
Glad it's working for you! Thanks for confirming it will mount automatically for you.

**Comment by surak** [comment] 2015-10-17 12:36
Can you post the binary so others don't have to suffer as you already did? :-)

**Comment by muammar** [comment] 2015-10-17 13:31
@surak You can install the version that is published by @alperakcan in sourceforge. That's what I used.

**Comment by jgclark** [comment] 2015-10-22 03:53
@muammar Thanks for the tip. For others, it's at http://sourceforge.net/projects/fuse-ext2/?source=directory

**Comment by Gminded** [comment] 2015-10-22 09:31
@jgclark The only version at sourceforge is 0.0.7, as far as I know. That doesn't appear to work in El Capitan (at least on my machine).

Actually the latest version didn't work well for me either, it just generates lots of Untitled volumes, but I suspect that something went wrong when I compiled it.

**Comment by surak** [comment] 2015-10-22 12:04
@muammar it does not work for el capitan.

**Comment by muammar** [comment] 2015-10-23 22:35
You have to disable  `csrutil`:

```bash
muammar@zarathustra ⮀ ~ ⮀ csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

<img width="986" alt="screen shot 2015-10-24 at 00 30 43" src="https://cloud.githubusercontent.com/assets/954209/10706388/d2126dde-79e6-11e5-971d-c1b0fd14e43f.png">

<img width="962" alt="screen shot 2015-10-24 at 00 31 11" src="https://cloud.githubusercontent.com/assets/954209/10706393/d8c13b24-79e6-11e5-916b-7ef9c0e9b8a0.png">

<img width="668" alt="screen shot 2015-10-24 at 00 31 35" src="https://cloud.githubusercontent.com/assets/954209/10706395/e085ae26-79e6-11e5-8b0d-86d98886d760.png">

<img width="1280" alt="screen shot 2015-10-24 at 00 34 24" src="https://cloud.githubusercontent.com/assets/954209/10706421/06c4fab0-79e7-11e5-9876-284e488233ca.png">

It does work.

**Comment by vult2000** [comment] 2015-11-13 01:43
I can't make it work.  I'm fairly certain the build is completing and it installs (I did the csrutil fix), but it will not mount regardless of which method I choose.  Whether I issue the command as:

mount -t fuse-ext /dev/disk2s2 /Volumes/Linux

-or-

fuse-ext /dev/disk2s2 /Volumes/Linux

neither command issues any error messages, but the disk does not mount.  I watch the system.log when running the commands and nothing shows there either.  I'm stumped.  If I open the System Prefs I see the same thing as you (except 0.09 for the fuse-ext2 version).  

Any ideas?

**Comment by gregdaynes** [comment] 2015-12-08 21:18
@vult2000 Try sudo, and make sure you make the director Linux in /Volumes
```
mkdir /Volumes/Linux
sudo fuse-ext /dev/disk2s2 /Volumes/Linux
```

**Comment by alamaz** [comment] 2015-12-09 08:14
I have a similar issue on OS X 10.11.1, using fuse 2.8.2 and fuse-ext2 0.0.9. Fuse-ext2 correctly shows up in preference pane.

> sudo fuse-ext2 /dev/disk3s2 /Volumes/Linux -o verbose
This command doesn't work, and doesn't give error message

> sudo mount -t fuse-ext2 /dev/disk2s2 /Volumes/Linux
This command gives me a blank message box : 
<img width="532" alt="capture d ecran 2015-12-09 a 09 03 38" src="https://cloud.githubusercontent.com/assets/1128664/11679870/99b9bd6a-9e54-11e5-8c14-d465607a2d61.png">

Have you got any idea ?

**Comment by alamaz** [comment] 2015-12-09 09:27
@vul2000 @gregdaynes I had a similar problem (no mount and no error message)
the trick was to use sudo for mkdir and fuse-ext as well (permissions issue)

**Comment by jstep322** [comment] 2015-12-24 09:26
I cannot get this to work. My problem is similar to @vult2000.

Running OS X  El Capitan 10.11.2.
I installed Fuse 2.8.2 from their website.
After disabling `csrutil`, I installed fuse-ext2 0.0.7 from the sourceforge link.

However, when I try to run: `sudo mount -t fuse-ext2 /dev/disk1s1 /Volumes/Linux`
A window pops up with the following error:

```
FUSE-EXT2 could not mount /dev/disk1
at /Volumes/Linux because the following problem occurred:

fuse-ext2: version:'0.0.7', fuse_version:'27' [main (../../fuse-ext2/fuse-ext2.c:324)]
fuse-ext2: enter [do_probe (../../fuse-ext2/do_probe.c:30)]
fuse-ext2: Error while trying to open /dev/disk1 (rc=13) [do_probe (../../fuse-ext2/do_probe.c:34)]
fuse-ext2: Probe failed [main (../../fuse-ext2/fuse-ext2.c:340)]
```

And when I try to run: `sudo fuse-ext2 /dev/disk1s1 /Volumes/Linux`, the command completes without printing an error, but the disk is not mounted.

Does it matter that I am using `fuse-ext2` instead of `fuse-ext`?

I also tried this with fuse-ext2 0.0.9, and I get the same popup window but no error.

**Comment by matjack1** [comment] 2016-01-09 20:55
I have the exact same problem as @jstep322, but with an ext3 filesystem.

**Comment by chunkster29** [comment] 2016-01-26 21:10
I've got it working using the Official Version from http://prdownloads.sourceforge.net/fuse-ext2/fuse-ext2-0.0.7.dmg?download using osx fuse 2.8.3 tested on both Yosemite and El Capitan with SIP turned off if have it installed already  remove with sudo make uninstall from the directory you installed it from and install the dmg version

**Comment by eblot** [comment] 2016-02-11 10:52
Installing to /Library rather than to /System/Library does help: 95c8e5f6b416b061f941bcd4333ff0bd32fa00f9
The latest version (v0.0.9) works on El Capitan w/o messing with SIP settings

    $  csrutil status
    System Integrity Protection status: enabled.
    $ mount | grep ext2
    /dev/disk4s2 on /Volumes/Development/root (osxfusefs_ext2, local, synchronous)
    $ df | grep disk4s2
    /dev/disk4s2                        29688888    595752  27585024     3%     2243   940605    0%   /Volumes/Development/root

**Comment by RobertJansson** [comment] 2016-03-11 18:43
I deployed a computer with OS X 10.11.3, compiled and installed the myriad of tools needed and disabled rootless before it successfully compiled. It was a hassle to get the binary but it's now working when put in /Library/FileSystems. Made the folder and mounted with:
`/usr/local/bin/fuse-ext2 /dev/disk1s1 /Volumes/Linux`

**Comment by Michelasso** [comment] 2016-03-17 11:33
@RobertJansson   Any chance we can get the 0.0.9 binary for El Capitan already compiled?

**Comment by RobertJansson** [comment] 2016-03-19 15:43
I would absolutely upload that but only if that doesn't violate any license? Can anyone tell if such distribution must contain any documents and also let me know if you know any good distribution model? Can we do it here somehow?

**Comment by Michelasso** [comment] 2016-03-19 17:44
I think that if you fork this project and add the download there it should be fine. As long as the code and any change you make stay in public domain. Although I believe the best solution would be if the master could integrate your changes. But I'm not really an expert of this legal stuff.

**Comment by RobertJansson** [comment] 2016-03-19 17:52
There is no change in code but a huge hassle to setup the full environmental, build and compile. I'll try and upload a simple installer here but make sure it doesn't surface or re-distributes elsewhere. I truly hope someone delete this post if there are any form of violations because my true intention is to help.

Please try this installer and let me know if it does the job or if there are any problems. I have not bothered with certificate so control-click and select open to pass the quarantine. Two files will be installed:
```
/Library/Filesystems/fuse-ext2.fs (v.0.0.9)
/Library/PreferencePanes/fuse-ext2.prefPane (64 bit version)
```
Installer:
[fuse-ext2 (OSX 10.11).v0.0.9.pkg.zip](https://github.com/alperakcan/fuse-ext2/files/180935/fuse-ext2.OSX.10.11.v0.0.9.pkg.zip)

**Comment by Michelasso** [comment] 2016-03-20 08:16
Ok Robert, I could install the package with no issues as you can see on thus screenshot:

<img width="752" alt="screenshot 2016-03-20 09 11 05" src="https://cloud.githubusercontent.com/assets/2322927/13903440/c6e5670e-ee7b-11e5-8135-9ec5e2c99715.png">

The problem is that I have a couple of SD cards partitioned FAT32/ext4 (I think it was ext4) and only the FAT32 gets recognized. But I know the ext partitions were recognized in Yosemite.

Could it be because I've run 

sudo fuse-ext2.uninstall

before installing it? There are no fuse-ext2.* files in /use/local/bin either.

**Comment by Michelasso** [comment] 2016-03-20 09:04
I restored with Time Machine all fuse-ext2 files I uninstalled. This is what I get:

```
bash-3.2# fuse-ext2 -o rw+ /dev//disk3s2  /mnt
fuse-ext2: version:'0.0.7', fuse_version:'27' [main (../../fuse-ext2/fuse-ext2.c:324)]
fuse-ext2: enter [do_probe (../../fuse-ext2/do_probe.c:30)]
fuse-ext2: leave [do_probe (../../fuse-ext2/do_probe.c:55)]
fuse-ext2: opts.device: /dev//disk3s2 [main (../../fuse-ext2/fuse-ext2.c:351)]
fuse-ext2: opts.mnt_point: /mnt [main (../../fuse-ext2/fuse-ext2.c:352)]
fuse-ext2: opts.volname: sdext [main (../../fuse-ext2/fuse-ext2.c:353)]
fuse-ext2: opts.options: rw+ [main (../../fuse-ext2/fuse-ext2.c:354)]
fuse-ext2: parsed_options: rw,allow_other,local,noappledouble,fsname=/dev//disk3s2,fstypename=ext2,volname=sdext [main (../../fuse-ext2/fuse-ext2.c:355)]
fuse-ext2: mounting read-write [main (../../fuse-ext2/fuse-ext2.c:369)]
bash-3.2# touch /mnt/foo
bash-3.2# ls -l /mnt/foo 
-rw-r--r--  1 root  wheel  0 20 Mar 10:02 /mnt/foo
bash-3.2# rm /mnt/foo
```

So it partially works I suppose. Disk Utility doesn't recognize the ext partition, though.

**Comment by RobertJansson** [comment] 2016-03-20 09:47
You did exactly install what I exactly said and you can verify that opening the package in Installer and select show files. But you are right you also need the binaries so hope you can take them like this because putting them in the package require scripting and testing. Let me know if it's better.
[usr-local-bin.zip](https://github.com/alperakcan/fuse-ext2/files/181225/usr-local-bin.zip)

**Comment by Michelasso** [comment] 2016-03-20 09:54
Ok, I tested it now.  A couple of things:

- there are only 5 executables instead of 7 (missing mk2fs and e2label)
- It also miss the library. Indeed it fails:

```
bash-3.2# fuse-ext2 -o rw+ /dev//disk3s2  /mnt
dyld: Library not loaded: /usr/local/lib/libosxfuse.2.dylib
  Referenced from: /usr/local/bin/fuse-ext2
  Reason: Incompatible library version: fuse-ext2 requires version 12.0.0 or later, but libosxfuse.2.dylib provides version 10.0.0
Trace/BPT trap: 5
```

**Comment by RobertJansson** [comment] 2016-03-20 10:46
I don't know what is new in this so try take my lib.
[lib.zip](https://github.com/alperakcan/fuse-ext2/files/181241/lib.zip)
Man-page for /usr/local/share/man:
[man1.zip](https://github.com/alperakcan/fuse-ext2/files/181242/man1.zip)

**Comment by Michelasso** [comment] 2016-03-20 11:11
I don't know what the heck I did anymore. After installing the lib files it didn't work anymore. So I restored the lib and bin folders of /usr/local. And that didn't work either. I installed your apk and only the binary files (no libs) and now it works manually via command line. Disk Utility has no idea what that partition is, though. While "diskutil" instead does.

Well, it's better than nothing I suppose. Otherwise I'll fire up my Linux virtual machine. Thanks a lot anyway! :+1:  :)

**Comment by RobertJansson** [comment] 2016-03-20 14:00
It came to be quite messy and I should have made a complete package instead and taken the time to test it before. Glad you are sorted.

I mount the disk image I started from with the normal hdiutil attach, got the diskID and used fuse-ext2 to mount the volume. umount and hdiutil detach was used to remove the volume.
Sorry to say but Disk utility is a program I stopped using at OSX10.6 because it was very unreliable and limited. You should not even bother about the new version.

**Comment by Michelasso** [comment] 2016-03-21 08:54
Well, actually I used to like Disk Utility until Yosemite. I could do some neat stuff with it using the UI. Like resize a partition on the fly. Or format a partition in ext4. It's this new one in El Capitan that seems to have gone back to the stone age. I just upgraded to a new MBP (and with it to El Capitan), I couldn't believe my eyes.

Anyway, now I don't remember well (I don't really use Linux filesystems much, but when I do I'd love to do it from the Finder), but I think in Yosemite fuse-ext2 was auto-mounting the ext partitions. Is that working for you or it's gone?

**Comment by danieltroger** [comment] 2016-03-21 08:57
It's gone.

**Comment by RobertJansson** [comment] 2016-03-21 10:21
The new version is very beautiful but the usefulnes was really gone a long time ago. Try to make the 650 MB recovery partition and get it right in the old version and you see some real flaws. A disk utility that can't even get the numbers right, mix bit with bytes, can't reach the partition type the OS require etc is not a good tool for more than monitoring. I must say I almost like the new version better for overview (but that is personal).
Just write your own tool for mounting or automate by probing for changes on the bus.

**Comment by LouisCAD** [comment] 2016-03-28 14:27
@eblot Do you have a compiled binary to let us try it without having to disable SIP?

**Comment by gpz500** [comment] 2016-04-07 21:02
I made a binary package without having to disable SIP. You can download it from here: https://github.com/gpz500/fuse-ext2/releases/tag/v0.0.9-gpz500. Glad if you try it ;-).

**Comment by manuelnaranjo** [comment] 2016-04-08 01:30
Works pretty well for me, now I can mount my 1TB ext4 HD

**Comment by jd4ever** [comment] 2016-04-26 13:37
gpz500, thank you! It works!


I have been able to mount the drive using the following command typed into Terminal
```
mkdir /Volumes/Linux
sudo mount -t fuse-ext2 /dev/disk2s6 /Volumes/Linux
```
http://apple.stackexchange.com/a/150241

**Comment by Battant** [comment] 2016-05-01 00:59
Hello,

I have an ext4 hard disk and I tried to upgrade my system to os x et captain but the fuse2.ext2 extention don't work,
I have fond this :

http://apple.stackexchange.com/questions/210198/mount-ext4-on-el-capitan

Could you help me to fix this bug ?

Best regards

Battant

**Comment by Battant** [comment] 2016-05-01 01:09
Hello,

I have found this article in french ;

http://www.digitalspirit.org/blog/index.php/post/2009/10/12/Monter-une-partition-ext2,-ext3-ou-ext4-sur-MacOs

Could you help me to found and extension make this action automatically ?

Best regards

Battant

**Comment by soerenkampschroer** [comment] 2016-05-07 12:48
@gpz500 Glad to report that it works for me as well. Only annoyance is that it can only be mounted through command line and I get "This disk you inserted was not readable by this computer" message every time I log in.

Is there any eta on proper support for 10.11?

**Comment by gpz500** [comment] 2016-05-08 18:40
@soerenkampschroer I had a similar annoyance with an USB memory stick. The problem was that the ext4 volume didn't have any label. Please make sure that your volume has a label, and that _/usr/local/opt/e2fsprogs/sbin/e2label_, which is pointed by _/usr/local/sbin/e2label_ symbolic link, is present and working.

**Comment by soerenkampschroer** [comment] 2016-05-09 13:03
@gpz500 Thanks for the advice. I checked and e2label is present in both locations. I assume by label you mean the partition name? If so, it's called "Data". If I mount my drive like so:

`mkdir /Volumes/Linux`
`sudo mount -t fuse-ext2 /dev/disk0s1 /Volumes/Linux`
`open /Volumes`

The drive will be correctly named "Data" instead of "Linux" which would be the mountpoint. It's not showing up in the sidebar and it doesn't auto-mount. If I do `ls /Volumes` it shows the folder named "Linux"..

**Comment by askerlee** [comment] 2016-05-23 13:23
@gpz500  thank you! You saved my day.

**Comment by Soraph** [comment] 2016-06-09 12:59
@gpz500 I tried your solution but I get a blank error message when I try to mount the partition, anything I can do about?

**Comment by gpz500** [comment] 2016-06-09 18:54
Hello @Soraph! Are you trying to mount the partition manually (from the terminal, with commands `fuse-ext2` or `mount_fuse-ext`) or automatically (at the insertion of an external drive/USB stick/SD card)?
What does it appear in the log files (file `/var/log/fuse-ext2_util.log` and Console app)?

**Comment by Soraph** [comment] 2016-06-09 20:14
I forgot manners sorry, good evening @gpz500 :)

I was trying with a manual mount, the log say:

> 2016-06-09 19:47:23: fuse-ext2 script invoked with command line "/Library/Filesystems/fuse-ext2.fs/Contents/Resources/../../fuse-ext2.util" "-p" "disk2s3" "removable" "readonly" "" "" "" "" ""
2016-06-09 19:47:23: Invoking user: root
2016-06-09 19:47:23: [Probe] Entering function Probe...
2016-06-09 19:47:23: [Probe] Executing "/usr/local/bin/fuse-ext2.probe" "/dev/disk2s3" 2>&1
2016-06-09 19:47:23: [Probe]   Return value: 252
2016-06-09 19:47:23: [Probe]   Volname     :
2016-06-09 19:47:23: [Probe]   Output (PROBE_OUTPUT): ""
2016-06-09 19:47:23: [Probe] PROBE_RETVAL indicated that we can not mount this volume.
2016-06-09 19:47:23: [Probe] returning FSUR_UNRECOGNIZED

The terminal popup said nothing at all, just that the error is "     ", I managed to read the partition byusing vbox and linux, still it was a long road compared to what seems the solution offered by this software.

**Comment by gpz500** [comment] 2016-06-09 21:56
It seems that `fuse-ext2.probe` doesn't recognize /dev/disk2s3 as a valid, or error free, ext2/ext3/ext4 filesystem.

What does it happen if you run directly `fuse-ext2`?
```
$ sudo fuse-ext2 /dev/disk2s3 /path/to/mount/point
$ echo $?
```

And, what about the output of this
`$ sudo /usr/local/opt/e2fsprogs/sbin/tune2fs -l /dev/disk2s3`
... and this?
`$ sudo /usr/local/opt/e2fsprogs/sbin/e2fsck /dev/disk2s3`

**Comment by Soraph** [comment] 2016-06-10 07:43
`$ sudo fuse-ext2 /dev/disk2s3 ....`
It say 252

`$ sudo /usr/local/opt/e2fsprogs/sbin/tune2fs -l /dev/disk2s3`
It say

> tune2fs 1.42.13 (17-May-2015)
/usr/local/opt/e2fsprogs/sbin/tune2fs: Bad magic number in super-block while trying to open /dev/disk2s3
Couldn't find valid filesystem superblock.

`$ sudo /usr/local/opt/e2fsprogs/sbin/e2fsck /dev/disk2s3`
It say

> e2fsck 1.42.13 (17-May-2015)
ext2fs_open2: Bad magic number in super-block
/usr/local/opt/e2fsprogs/sbin/e2fsck: Superblock invalid, trying backup blocks...
/usr/local/opt/e2fsprogs/sbin/e2fsck: Bad magic number in super-block while trying to open /dev/disk2s3

> The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

If I read this well, OSX think the hd is damaged somehow?

**Comment by gpz500** [comment] 2016-06-10 08:22
Yes: damaged, or /dev/disk2s3 is not an ext2/ext3/ext4 filesystem.
Please, run the commands `tune2fs -l` and `e2fsck` also under Linux, in order to be sure that the filesystem is not corrupted.
And, under Mac OS X, run `diskutil list`, in order to be sure that /dev/disk2s3 is the right device file to use.

**Comment by Soraph** [comment] 2016-06-11 09:06
Linux said:

> tune2fs 1.42.13 (17-May-2015)
tune2fs: Bad magic number in super-block while trying to open /dev/sdb3
Couldn't find valid filesystem superblock.

> e2fsck 1.42.13 (17-May-2015)
/dev/sdb3 is mounted.
e2fsck: Cannot continue, aborting.

Mac OSX confirms that I'm using the right device for my commands

**Comment by gpz500** [comment] 2016-06-11 10:43
Sorry for the missing info: please repeat the commands on Linux after having unmounted /dev/sdb3:
```
$ sudo umount /dev/sdb3
$ sudo tune2fs -l /dev/sdb3
$ sudo e2fsck -f /dev/sdb3
```
Note that I added the option `-f` to e2fsck, to force the filesystem check even if it seems clean.
With no errors `tune2fs -l` should print the content of the superblock.

**Comment by Soraph** [comment] 2016-06-13 16:20
Sorry for the delay, even with this procedure the results are the same, I believe that at this point the HD is damaged and there is no point in "polluting" the conversation anymore, I think I'll try to format it and try again :)

**Comment by muammar** [comment] 2016-09-20 21:48
Just for information, the binary from @gpz500 works for macOS Sierra.

**Comment by surak** [comment] 2016-09-25 21:24
It stopped working with Sierra. Anyone tried it?

**Comment by muammar** [comment] 2016-10-25 00:16
@surak it's stopped for me as well... I cannot access my partitions anymore :(. Nor even with @gpz500 package.

**Comment by hamsternik** [comment] 2016-11-22 09:20
@RobertJansson tnx a lot, just installed your pkg on the macOS 10.12.1 and it works fine!

**Comment by Battant** [comment] 2016-11-22 10:23
Hello,

I could'nt build fuse-ext2 because I could'nt build a dependence.

See for more detail :

https://github.com/alperakcan/fuse-ext2/issues/10#issuecomment-262188021

Best regards

Battant

**Comment by Battant** [comment] 2016-11-22 10:24
https://github.com/alperakcan/fuse-ext2/issues/10#issuecomment-262188021

**Comment by Battant** [comment] 2016-11-22 10:25
https://github.com/alperakcan/fuse-ext2/issues/10

**Comment by Ole2mail** [comment] 2017-05-14 11:14
OS version: "macOS Sierra 10.12.4"
Darwin Johns-MBP 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
Homebrew/homebrew-core (git revision 2128; last commit 2017-05-13)

at first - build with "XCode command line tools" is not going to work:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

so you have to install complete XCode (to have it in the Applications folder for example) and to apply following command ahead of making fuse-ext2:

sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

at second - ext2fs_open is inside e2fsprogs which is available to install from homebrew with the following command:

brew install e2fsprogs

but the configure will fail to find the libext2fs.a on a standard path so the only following one worked for me:

CFLAGS="-idirafter/opt/gnu/include -idirafter/usr/local/include/osxfuse/ -idirafter/$(brew --prefix e2fsprogs)/include" LDFLAGS="-L/usr/local/opt/glib -L/usr/local/lib -L$(brew --prefix e2fsprogs)/lib" ./configure

now everything will compile successfully.

** BUILD SUCCEEDED **

attaching build complete package 
[fuse-ext2-0.0.9.zip](https://github.com/alperakcan/fuse-ext2/files/999286/fuse-ext2-0.0.9.zip)
 for someone just in case

**Comment by muammar** [comment] 2017-05-14 15:23
@Ole2mail holy s%%#!!!!. This one is working. Thanks!.

**Closed** 2017-05-26 17:08 UTC

**Comment by BrainBurnerCO** [comment] 2017-08-03 15:23
@Ole2mail built it and installed, but it fails to mount the partition. It says "Uninitialized fuse-ext2" on Disk Utils. Do I still need to disable SIP for it to work? Yes, Fuse is installed if that matters.
![screen shot 2017-08-03 at 11 20 45 am](https://user-images.githubusercontent.com/550657/28929449-f010e8ea-783d-11e7-9d47-af5d0e683d77.png)
![screen shot 2017-08-03 at 11 22 56 am](https://user-images.githubusercontent.com/550657/28929537-2cdd471e-783e-11e7-8039-ef48084c6cd7.png)
![screen shot 2017-08-03 at 11 23 13 am](https://user-images.githubusercontent.com/550657/28929541-2eb2530e-783e-11e7-907e-8d87f3a5c08a.png)

**Comment by frspp** [comment] 2017-10-19 15:36
@Ole2mail 
"attaching build complete package: fuse-ext2-0.0.9.zip"
Thanks for it! First writes and booting ext4 system after that worked (osx10.11.6)!

FYI for others: after installing package no need to run the write support command mentioned in https://github.com/osxfuse/osxfuse/wiki/Ext .

**Comment by jjmaestro** [comment] 2018-01-20 15:05
Yay! Thanks @Ole2mail for the fix :) I followed your suggestions and I managed to change the installation script and make it work in 10.12.6. Now, let's see if it actually works and I can read an ext3 hard drive... XD
